
version: "3.8"
services:
  postgres:
    container_name: postgres_work_with_db
    image: postgres:16.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres_work_with_db
      PGDATA: /data/postgres
    volumes:
      - ./assets/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/data/postgres
    ports:
      - "5435:5432"
    restart: unless-stopped

volumes:
  pgdata: